---
title: "Pitcher WAR"
output: html_document
---

```{r}
library(tidyverse)
setwd("/Users/Chris/Dropbox/School Stuff/BST 260 Data Science/baseball2017")
warps <- read.csv("warpitchplus.csv",stringsAsFactors=FALSE)
names <- read.csv("Teams.csv",stringsAsFactors=FALSE)

names <- names %>% select(yearID,teamID,teamIDBR,teamIDlahman45,teamIDretro,franchID,W,L,Rank)
names <- names %>% filter(yearID>1984 & yearID<2017)

warps <- warps %>% filter(yearID>1984 & yearID<2017)
warps$WAR <- as.numeric(warps$WAR)

warpteam <- warps %>% na.omit() %>% group_by(yearID,teamID) %>% 
  summarize(
            medWAR = median(WAR),
            q90WAR = quantile(WAR,0.9),
            q75WAR = quantile(WAR,0.75),
            q25WAR = quantile(WAR,0.25),
            q10WAR = quantile(WAR,0.1),
            sdWAR = sd(WAR),
            WARtot = sum(WAR),
            salteam = sum(salary))

warpteam %>% ggplot(aes(yearID,medWAR,fill=factor(yearID))) + 
  geom_boxplot(na.rm = TRUE) + theme(legend.position="none") + 
  scale_x_continuous(breaks = seq(1985,2015,5)) + 
  labs(y = "Median WAR (by team)")
```

```{r}
warpteam$franchID = ""
warpteam$wlratio = 0
warpteam$rank = 0
for (i in 1:nrow(warpteam)){
  nameyear <- names %>% filter(yearID==warpteam$yearID[[i]])
  nameab <- nameyear %>% filter(nameyear$teamIDBR==warpteam$teamID[[i]])
  warpteam$franchID[[i]] = nameab$franchID[[1]]
  warpteam$wlratio[[i]] = nameab$W[[1]]/nameab$L[[1]]
  warpteam$rank[[i]] = nameab$Rank[[1]]
}

#order franchises by total WAR prior to the year 2000
allwarp <- warpteam %>% filter(yearID<2000)
allwarp <- allwarp %>% group_by(franchID) %>% summarize(wartot=sum(medWAR))
allwarp <- allwarp %>% arrange(wartot) #ascending
#allwarp <- allwarp %>% arrange(desc(wartot)) #descending
allwarp$rank <- c(1:nrow(allwarp))
allwarp$franfct <- allwarp$rank
allwarp$franfct <- factor(allwarp$franfct,levels=allwarp$rank,labels=allwarp$franchID)

warpteam$franfct <- allwarp$franfct[[1]]
for (i in 1:nrow(warpteam)){
  warpteam$franfct[[i]] <- allwarp$franfct[which(allwarp$franchID==warpteam$franchID[[i]])]
}
```

```{r}
warpteam %>% ggplot() + geom_tile(aes(x=yearID,y=factor(franfct),fill=medWAR)) + 
  scale_x_continuous(breaks = seq(1985,2015,5)) + 
  #scale_y_discrete(labels = rev(allwar$franchID)) +
  scale_fill_gradient(low="#00007F", high="red", name="Median\nWAR") +
  geom_vline(aes(xintercept=1994),linetype=3,size=1, color="white") +
  labs(x="Year",y="Team/Franchise")

warpteam %>% ggplot() + geom_tile(aes(x=yearID,y=factor(franfct),fill=q75WAR)) + 
  scale_x_continuous(breaks = seq(1985,2015,5)) + 
  #scale_y_discrete(labels = rev(allwar$franchID)) +
  scale_fill_gradient(low="#00007F", high="red", name="WAR, 75th\npercentile") +
  geom_vline(aes(xintercept=1994),linetype=3,size=1, color="white") +
  labs(x="Year",y="Team/Franchise")
```

```{r}
#Previously calculated salary changes and performance changes year-to-year and saved in warplus.csv
warpstats <- warps #%>% filter(pitcher=="Y")
warpstats <- warpstats[c("playerID","yearID","teamID",
                       "WAA",
                       "WAR",
                       "prevWAA",
                       "prevWAR",
                       "dWAA",
                       "dWAR",
                       "salary","bump","cut","dsal","pdsal")]
warpstats <- warpstats %>% filter(yearID > 1985)

warpstats <- warpstats %>% filter(dsal!=0)
warpstats <- warpstats %>% filter(abs(dsal)>1)

w2 <- warpstats %>% filter(yearID==1991)
#get est and r^2 by year?
summary(lm(w2$dsal~w2$prevWAR))
summary(lm(w2$dsal ~ w2$prevWAR + w2$dWAR) )
```

```{r,echo=FALSE}
w2 <- warpstats

library(broom)
regres <- w2 %>% group_by(yearID) %>% do(glance(lm(salary ~ prevWAR,data=.)))

regres %>% ggplot() + geom_bar(aes(yearID,adj.r.squared,fill=adj.r.squared),stat="identity") +
    scale_x_continuous(limits = c(1984,2016), breaks=seq(1985,2015,5)) +
    scale_fill_distiller(palette = "Spectral",breaks=seq(0,70,20),name="Percent") +
    geom_text(aes(x=1994,y=0.02),label="STRIKE",angle=90,hjust = 0,color="white") +
    geom_text(aes(x=1986,y=.5),label="CBA6",hjust = 0,color="black",size=3.5) +
    geom_text(aes(x=1990.5,y=.5),label="CBA7",hjust = 0,color="black",size=3.5) +
    geom_text(aes(x=1997,y=.5),label="CBA8",hjust = 0,color="black",size=3.5) +
    geom_text(aes(x=2003,y=.5),label="CBA9",hjust = 0,color="black",size=3.5) +
    geom_text(aes(x=2007.2,y=.5),label="CBA10",hjust = 0,color="black",size=3.5) +
    geom_text(aes(x=2012,y=.5),label="CBA11",hjust = 0,color="black",size=3.5) +
    geom_vline(aes(xintercept=1989.5),linetype=3, color="black") +
    geom_vline(aes(xintercept=1993.5),linetype=3, color="black") +
    geom_vline(aes(xintercept=1994.5),linetype=3, color="black") +
    geom_vline(aes(xintercept=2001.5),linetype=3, color="black") +
    geom_vline(aes(xintercept=2006.5),linetype=3, color="black") +
    geom_vline(aes(xintercept=2010.5),linetype=3, color="black")
```



```{r,echo=FALSE}
w2 <- warpstats

library(broom)
regres <- w2 %>% group_by(yearID) %>% do(glance(lm(salary ~ WAR,data=.)))

regres %>% ggplot() + geom_bar(aes(yearID,adj.r.squared,fill=adj.r.squared),stat="identity") +
    scale_x_continuous(limits = c(1984,2016), breaks=seq(1985,2015,5)) +
    scale_fill_distiller(palette = "Spectral",breaks=seq(0,70,20),name="Percent") +
    geom_text(aes(x=1994,y=0.02),label="STRIKE",angle=90,hjust = 0,color="white") +
    geom_text(aes(x=1986,y=.4),label="CBA6",hjust = 0,color="black",size=3.5) +
    geom_text(aes(x=1990.5,y=.4),label="CBA7",hjust = 0,color="black",size=3.5) +
    geom_text(aes(x=1997,y=.4),label="CBA8",hjust = 0,color="black",size=3.5) +
    geom_text(aes(x=2003,y=.4),label="CBA9",hjust = 0,color="black",size=3.5) +
    geom_text(aes(x=2007.2,y=.4),label="CBA10",hjust = 0,color="black",size=3.5) +
    geom_text(aes(x=2012,y=.4),label="CBA11",hjust = 0,color="black",size=3.5) +
    geom_vline(aes(xintercept=1989.5),linetype=3, color="black") +
    geom_vline(aes(xintercept=1993.5),linetype=3, color="black") +
    geom_vline(aes(xintercept=1994.5),linetype=3, color="black") +
    geom_vline(aes(xintercept=2001.5),linetype=3, color="black") +
    geom_vline(aes(xintercept=2006.5),linetype=3, color="black") +
    geom_vline(aes(xintercept=2010.5),linetype=3, color="black")
```

```{r}
addcba <- function(df){
  df$cba = .bincode(df$yearID,c(0,1993.5,1994.5,2002,2006,2010,10000))
  df$cba = ifelse(df$cba>2,df$cba+5,df$cba)
  df$cba = ifelse(df$cba==1,df$cba+6,df$cba)
  df$cba = ifelse(df$cba==2,NA,df$cba)
  df
}

regres <- addcba(regres)

anova.reg <- aov(adj.r.squared ~ as.factor(cba),data=regres)
summary(anova.reg)
TukeyHSD(anova.reg)
```

```{r}
regres %>% ggplot() + geom_point(aes(cba,adj.r.squared))
```
















