---
title: "Baseball01"
output: html_document
---

```{r}
library(tidyverse)
setwd("/Users/Chris/Dropbox/School Stuff/BST 260 Data Science/baseball")
salaries <- read.csv("salary.csv")
batting <- read.csv("batting.csv")

salaries <- salaries %>% filter(year > 1969)
salaries$player_id <- as.character(salaries$player_id)
batting <- batting %>% filter(year > 1969)

salaries <- salaries[order(salaries$player_id,salaries$year),]
```

Determine salary bumps/reductions
```{r}
players <- unique(salaries$player_id)
salaries$bump = 0
salaries$cut = 0
salaries$dsal = 0
player1 <- salaries$player_id[[1]]
for (i in 2:nrow(salaries)) {
  if (salaries$player_id[[i]] == player1){
    if (salaries$salary[[i]] > salaries$salary[[i-1]]){
      salaries$bump[[i]] = 1
    }
    else if (salaries$salary[[i]] < salaries$salary[[i-1]]){
      salaries$cut[[i]] = 1
    }
    salaries$dsal[[i]] = salaries$salary[[i]] - salaries$salary[[i-1]]
  }
  else{
    player1 <- salaries$player_id[[i]]
  }
}
```

Calculate On-base Plus Slugging (OPS)
```{r}
batting$player_id <- as.character(batting$player_id)
batting <- batting[order(batting$player_id,batting$year),]
batting <- batting %>% mutate(single=h-(double+triple+hr), #singles
                              tb=single*1+double*2+triple*3+hr*4, #total bases
                              slg=tb/ab, #slugging
                              obp=(h+bb+hbp)/(ab+bb+sf+hbp), #on base percentage
                              ops=slg+obp)

#filter out players with low At Bats in order to reduce artificially high OPS
#there are ~160 games per season, cutoff of 16 At Bats ~= played 10% of games w/conservative assumption of only 1 AB per game
batting <- batting %>% filter(ab > 16)
```
Calculate changes in OPS year-on-year
```{r}
batting$dOPS = 0
batting$prevOPS = 0
player1 <- batting$player_id[[1]]
for (i in 2:nrow(batting)) {
  if (batting$player_id[[i]] == player1){
    batting$dOPS[[i]] <- batting$ops[[i]] - batting$ops[[i-1]]
    batting$prevOPS[[i]] <- batting$ops[[i-1]]
  }
  else{
    player1 <- batting$player_id[[i]]
    i = i+1
  }
}


batting <- batting[order(-batting$ops),]
```

```{r}
opsonly <- batting[c("player_id","year","team_id","ops","dOPS","prevOPS")]
#sal2 <- merge(opsonly,salaries,by=c("player_id","year"),all=TRUE)
sal2 <- merge(opsonly,salaries,by=c("player_id","year","team_id"))
sal2 <- sal2[order(sal2$player_id,sal2$year),]
sal2bumps = sal2 %>% filter(bump > -1)
sal2cuts = sal2 %>% filter(cut > -1)
```

```{r}
ggplot(sal2bumps) + geom_point(aes(prevOPS,bump)) + 
  stat_smooth(aes(prevOPS,bump),method = "glm", method.args = list(family = "binomial")) +
  labs(x = "OPS in previous year", y = "Probability of a salary increase")

ggplot(sal2cuts) + geom_point(aes(prevOPS,cut)) + 
  stat_smooth(aes(prevOPS,cut),method = "glm", method.args = list(family = "binomial")) +
  labs(x = "OPS in previous year", y = "Probability of a salary decrease")

#geom_hex?
```
Seems to be a relationship for bumps, not so much for cuts. The significance in the logistic regression may simply be from inflation.

```{r}
sal2bumps %>% filter(bump==1) %>% ggplot() + geom_histogram(aes(prevOPS)) 
sal2bumps %>% filter(bump==0) %>% ggplot() + geom_histogram(aes(prevOPS)) 

sal2cuts %>% filter(cut==1) %>% ggplot() + geom_histogram(aes(prevOPS)) 
sal2cuts %>% filter(cut==0) %>% ggplot() + geom_histogram(aes(prevOPS)) 
#geom_hex?
```

```{r}
model <- glm(bump ~ prevOPS,family=binomial(link='logit'),data=sal2bumps)
summary(model)
model <- glm(cut ~ prevOPS,family=binomial(link='logit'),data=sal2cuts)
summary(model)

model <- glm(bump ~ dOPS,family=binomial(link='logit'),data=sal2bumps)
summary(model)
model <- glm(cut ~ dOPS,family=binomial(link='logit'),data=sal2cuts)
summary(model)
```



